"""Preserved-source integration export. Blender --background SOURCE --python this -- OUTPUT."""
import bpy, sys, json, hashlib, shutil
from pathlib import Path
from collections import Counter
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
import babylon_js
babylon_js.register()
from babylon_js.json_exporter import JsonExporter

source = Path(bpy.data.filepath)
original_hash = hashlib.sha256(source.read_bytes()).hexdigest()
out = Path(sys.argv[sys.argv.index('--')+1]).resolve()
out.mkdir(parents=True, exist_ok=False)
scene = bpy.context.scene
visible = [o for o in scene.objects if o.type == 'MESH' and o.get('role') == 'VISIBLE_DELIVERY_AND_BAKE_RECEIVER']
assert len(visible) == 633, 'Unexpected source: review the delivery manifest first'
helpers = [o for root in ['physicsObjects','navMeshFloor'] for o in bpy.data.objects[root].children_recursive if o.type=='MESH']
chosen = set(visible + helpers)
for o in list(chosen):
    parent = o.parent
    while parent:
        chosen.add(parent)
        parent = parent.parent
assert len(helpers) == 29
lightmap = source.parent / 'maps/mirror8_final.exr'
assert lightmap.is_file()
assert hashlib.sha256(lightmap.read_bytes()).hexdigest() == '27c6f5afe513ac783f17f673f6947445af954534c699aa6c85fc7a3f9b657b31'
root = next(o for o in chosen if o.name.startswith('lightmap_'))
old_name = root.name
root.name = 'lightmap_' + lightmap.stem
scene.world.usePBRMaterials = True
scene.world.positionsPrecision = 6
scene.world.normalsPrecision = 6
scene.world.UVsPrecision = 6
scene.world.textureDir = 'textures'
scene.world.inlineTextures = False
scene.world.skyBox = False
scene.camera = None
dg = bpy.context.evaluated_depsgraph_get()
counts = {}
for group, objects in [('visible',visible),('helpers',helpers)]:
    count = 0
    for o in objects:
        e=o.evaluated_get(dg); mesh=e.to_mesh();mesh.calc_loop_triangles()
        count += len(mesh.loop_triangles);e.to_mesh_clear()
    counts[group]=count
assert counts['visible'] == 20000
exporter = JsonExporter()
exporter.execute(bpy.context, str(out / 'grandBedroomDay.babylon'), sorted(chosen,key=lambda o:o.name))
assert not exporter.fatalError and exporter.nErrors == 0
shutil.copy2(lightmap, out / lightmap.name)
assert hashlib.sha256(source.read_bytes()).hexdigest() == original_hash
manifest = {'source':str(source),'source_sha256':original_hash,'blender':bpy.app.version_string,
    'counts':counts,'visible_names':[o.name for o in visible],'helper_names':[o.name for o in helpers],
    'export_names':[o.name for o in chosen],'lightmap':str(lightmap),'lightmap_sha256':hashlib.sha256(lightmap.read_bytes()).hexdigest(),
    'in_memory_changes':['Export selection: visible delivery meshes, physics/navigation helpers and their ancestors only.',
                         f'Lightmap marker {old_name} -> {root.name} to reference the latest mirrored map.',
                         'PBR export with 6 decimal geometry/UV precision; diagnostic/bake lights and cameras excluded.'],
    'source_unchanged':True,'warnings':exporter.nWarnings,
    'note':'EXR supplied as source; KaDshow requires separately converted KTX2. Runtime lighting/skybox assets are not generated by this test.'}
(out/'manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
print('BEDROOM_EXPORT_COMPLETE',json.dumps(counts),flush=True)
